FROM openjdk:11-jdk-alpine
MAINTAINER com.zsener
COPY target/ReadingIsGood-0.0.1-SNAPSHOT.jar ReadingIsGood-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/ReadingIsGood-0.0.1-SNAPSHOT.jar"]